### PR TITLE
start of 1.9 update.  New 1.9 materials added (hopefully)

### PR DESCRIPTION
**Pull request by Sycholic**

### CODE REVIEW

**Comment by Sleaker** [comment]
Thanks for the work, was there any reason you added the new materials at the top of the list instead of the bottom as traditional?

**Comment by xJovs** [comment]
I would also suggest you add "items.add(new ItemInfo("Dragon Head", new String[][]{{"drag", "head"}, {"drag", "skul"}}, Material.SKULL_ITEM, (short) 5));" for the Dragon Head.

**Comment by Sycholic** [comment]
was personal habit, keep my lists newest to oldest, my bad.

**Comment by Sleaker** [comment]
Also it looks like you commented out splash potions, are they gone in 1.9?

**Comment by Sycholic** [comment]
no they changed bigtime ... no more numerics still trying to figure that out... https://www.spigotmc.org/threads/what-has-changed-in-1-9-when-it-comes-to-creating-potions.131769/

**Pull request merged**
