### PR TITLE
Added @Deprecated to functions using double and adding functions with…

### PR DESCRIPTION
**Pull request by Zayceur**
… BigDecimal

### CODE REVIEW

**Comment by Zayceur** [comment]
#51

**Comment by Sleaker** [comment]
apparently you failed to read my comments on this.

**Comment by Vinetos** [comment]
I would like to have this one. Do you think it will be available ?

**Comment by Sleaker** [comment]
@Vinetos - this is not something that will ever be in the Vault API due to compatibility reasons.

**Comment by Vinetos** [comment]
If we deprecate "old-way" methods all is right

**Pull request closed without merging**
