### PR TITLE
Update bukkit version to 1.15.2

### PR DESCRIPTION
**Pull request by TheSirCororo**

### CODE REVIEW

**Comment by Geolykt** [comment]
Updating the bukkit version here would mean also bumping the bukkit version at https://github.com/MilkBowl/Vault and it's plugin.yml. I also don't think that it is "good" to update it without a more specific reason as it does not allow older versions of bukkit from loading the jar.

That being said, `api-version: 1.13` will probably get rejected by some future version (perhaps even 1.17?) so this could be covered as a preemptive measure

**Comment by Sleaker** [comment]
@Geolykt bukkit version referenced here literally only affects the version being built against. this PR does nothing as far as compatibility with runtime. api-version is a spigot construct alone.

**Comment by Geolykt** [comment]
> @Geolykt bukkit version referenced here literally only affects the version being built against. this PR does nothing as far as compatibility with runtime. api-version is a spigot construct alone and was added just to indicate compatibility there. It doesn't really have any other use case, as you mentioned, it may prevent Vault from loading if spigot decides to use to no longer load a plugin due to breaking change.

I am aware of this, but building against a newer version does not not eliminate the chance that a newer thing is made use of sometime in the future which could cause issues in older versions which may be hard to trace

**Comment by Sleaker** [comment]
@Geolykt Your statement is self-defeating... the only time Vault would break is because of an API change. This is why spigot uses an API versioning in the plugin.yaml to prevent that potential problem.  The result of that would be Vault just not loading at all.. but that's not happening.

**Pull request closed without merging**
