### PR TITLE
Correct itemByStack()

### PR DESCRIPTION
**Pull request by FlyingPikachu**
Fix for #36

### CODE REVIEW

**Comment by stuntguy3000** [comment]
Durability checking is now gone is it not?

**Comment by FlyingPikachu** [comment]
@stuntguy3000 Not entirely. Previously, checking durability via isDurable() for **all** ItemStacks caused materials without collision, like Buttons, to return as null. Now, durability is only checked if the ItemStack equates to a solid block (to account for variations like Smooth Brick and Red Wool).

**Comment by FlyingPikachu** [comment]
This should also resolve #10

**Comment by FlyingPikachu** [comment]
I shouldn't be doing this in the online editor. Closing so I can push this through an IDE.

**Pull request closed without merging**
